### ISSUE TITLE
Prise connectée ne fonctionne pas

### ISSUE THREAD

**Issue by GregBaum** [sasu-drooz/Domoticz-Rfplayer#10]
Bonjour,
Ma prise connectée CHACON fonctionne avec l'interface Java du RFPlayer:
Il est possible de l'associer.
Il est possible de l'allumer.
Il est possible de l'éteindre.

Par contre je ne peux pas la creer dans Domoticz, ni la détecter automatiquement.
A dispo pour fournir toute info complémentaire...

**Comment by zaraki673** [comment]
Bonjour, 
as-tu bien activé le mode Learning dans les paramètres ?
si oui, peux tu activer le mode debug et me transmettre les logs?

Merci ;)

**Comment by GregBaum** [comment]
Effectivement je n'ai pas utilisé de telecommande... Hum!
Tu dis que je dois associer avec la telecommande, puis appuyer sur 'on' en meme temps que je fais la detection auto dans les interrupteurs de domoticz? 
Ok... retry demain et je te dis.
Merci!

**Comment by zaraki673** [comment]
la telecommande va creer l interrupteur dans domoticz, 
ensuite il faudra de nouveau associer ta prise avec l interrupteur nouvellement creer dans domoticz (suite aux règles de non piratage mis en place par Ziblue)

de rien ;)

**Comment by GregBaum** [comment]
Salut,
Test effectué... et MDR La télécommande CHACON n'est pas captée par le RFP!!!

En bref les prises qui repondent bien à la télécommande sont inutiles car la télécommande ne parle pas au RFPlapyer. Les prises qui marchent avec le RFPlayer sous le Protocol Chacon ne peuvent être utilisée dans DOMOTICZ car je n'ai pas / plus de télécommande :D.
Ca sent la bouze de protocole.
Quoiqu'il en soit je n'ai rien qui permette d'indiquer un bug plugin et je crains que le matériel soit juste incompatible... 

On ferme cette issue sauf si tu souhaite la conserver.

**Comment by zaraki673** [comment]
as tu essayer avec le logiciel de configuration du rfplayer ? (les trames devrait etre vu, chacon c est le basic et du coup par le plugin )

je suis en train d ajouter une fonction d ajout manuel de telecommandes dans domoticz, comme ca tu pourras les associer sans telecommande ;)

**Comment by GregBaum** [comment]
Cool pour l'ajout manuel.
Oui j'ai essayé le configurateur, je me suis dit que je chopperai le signal avec le Parrot,  car tu l'as prévu dans le plugin. il a rien choppé. :)
Je vais continuer à m'acharner un peu dessus pour avoir plus d'éléments à remonter à tout le monde.

**Comment by zaraki673** [comment]
c'est bon pour l ajout manuel de devices ;)

**Comment by GregBaum** [comment]
Je vais tester ça!
En ce qui concerne la télécommande CHACON qui n'est pas captée c'est bien une histoire de protocole j'ai déterré que : CoCo GDR2 equal Chacon 54660 dans la doc RFX. (www.rfxcom.com/WebRoot/StoreNL2/Shops/.../RFXtrx_User_Guide_-_FR.pdf )
J'ai rendu les prises et changé pour des compatibles DIO et la detection auto fonctionne.
par contre si j'essaie d'envoyer ON ou OFF je trouve une erreur dans les logs:

La ligne ZIA++ON.CHACON.1590843008 me semble louche... je m'attendais plustot à A1
voici le log:

2017-05-06 16:16:10.748 (RFP1) SendtoRfplayer - Options find in DB: {'id_lsb': '17b495a', 'protocol': '4', 'id_msb': '1', 'id': '1590843008', 'infoType': '1'} for devices unit 2
2017-05-06 16:16:10.748 (Aquarium) Updating device from 0:'off' to have values 1:'on'.
2017-05-06 16:16:10.752 (RFP1) Sending 27 bytes of data:.
2017-05-06 16:16:10.752 (RFP1) 5a 49 41 2b 2b 4f 4e 20 43 48 41 43 4f 4e 20 31 35 39 30 38 ZIA++ON.CHACON.15908
2017-05-06 16:16:10.752 (RFP1) 34 33 30 30 38 0a 0d .. .. .. .. .. .. .. .. .. .. .. .. .. 43008..
2017-05-06 16:16:10.853 (RFP1) Received 67 bytes of data:.
2017-05-06 16:16:10.853 (RFP1) 5a 49 41 2d 2d 0a 65 72 72 6f 72 20 72 65 71 75 65 73 74 20 ZIA--.error.request.
2017-05-06 16:16:10.853 (RFP1) 6e 75 6d 62 65 72 3d 30 0a 53 79 6e 74 61 78 20 65 72 72 6f number=0.Syntax.erro
2017-05-06 16:16:10.853 (RFP1) 72 3a 20 4f 4e 20 43 48 41 43 4f 4e 20 31 35 39 30 38 34 33 r:.ON.CHACON.1590843
2017-05-06 16:16:10.853 (RFP1) 30 30 38 0a 0a 0a 0d .. .. .. .. .. .. .. .. .. .. .. .. .. 008....

**Comment by zaraki673** [comment]
hum, je regarde ca, 

effectivement pour l id utilisé il va falloir que je regarde pour la convertir au format A-P 1-15 ne pouvant utiliser l'id reçu pour l émission

merci

**Comment by zaraki673** [comment]
ca devrait etre corriger (sur les autres protocoles aussi au passage)

**Comment by GregBaum** [comment]
Je retest ! :)

**Comment by GregBaum** [comment]
Ca marche nickel.
