### ISSUE TITLE
X2D Microcox  - infotype 11

### ISSUE THREAD

**Issue by dfo92** [sasu-drooz/Domoticz-Rfplayer#23]
Bonjour,

Déjà un grand merci à zaraki673 pour son travail.

Je teste le contact de porte Micro Cox.
Il est est bien reconnu par RFPLAYER,
 
ZIA44 FRAME: frameType: 0, cluster: 0, dataFlag: 1, 
rfLevel: -60dBm, floorNoise: -105dBm, rfQuality: 10
protocol: 8 (X2D), infoType: 11, frequency: 868350Khz
subType: 0 (Detector/Sensor), id: 1112729857, qualifier: 2 (  Alarm)

mais j'obtiens cette erreur dans Domoticz (mode debug)

"Error while decoding or reading JSON"

J'ai mis en pj le log complet

Cordialement

DFO
[microcox.txt](https://github.com/sasu-drooz/Domoticz-Rfplayer/files/1151144/microcox.txt)

**Comment by zaraki673** [comment]
Merci pour la log ;)
dsl de pas avoir repondu plutot (we prolongé ;) )

je regarde ca

**Comment by dfo92** [comment]
Pas de soucis.Je teste quand tu veux ;-)DFOLe 17 juil. 2017 21:56, zaraki673 <notifications@github.com> a écrit :Merci pour la log ;)
dsl de pas avoir repondu plutot (we prolongé ;) )
je regarde ca

**Comment by zaraki673** [comment]
correction apporté : https://github.com/sasu-drooz/Domoticz-Rfplayer/commit/fae2a9ef3e09377af18257192834cdf2e421f199

;)

**Comment by dfo92** [comment]
Super rapide , je regarde ce soirDFOLe 18 juil. 2017 05:06, zaraki673 <notifications@github.com> a écrit :correction apporté : fae2a9e
;)

**Comment by dfo92** [comment]
Hello,

J'ai testé. La création du dispositif se passe bien :-) , mais il semble y avoir un problème de décodage. L'état du dispositif ne se met pas à jour.
Voilà le log
[erreur microcox-1.txt](https://github.com/sasu-drooz/Domoticz-Rfplayer/files/1156617/erreur.microcox-1.txt)

**Comment by zaraki673** [comment]
hum erreur au moment de la maj du status du device, j avais laisser la batterie sauf que j ai pas l info ... 🗡 
https://github.com/sasu-drooz/Domoticz-Rfplayer/commit/ea30ac9b8805814b2d4f8729168629175f3f5112

**Comment by dfo92** [comment]
Hello,
J'ai testé. L'erreur a disparue et le détecteur semble opérationnel, mais j'ai un problème de stabilité avec la dernière version beta 8094 de Domoticz qui plante (obligé de redémarré) . Je ne sais pas dire si c'est la version beta ou le plugin. Peut-être as-tu des infos. Je t'en dis plus dés que j'ai réussi à stabiliser.
Merci.

**Comment by zaraki673** [comment]
desactives le plugins et laisse en un autre activé voir si ca plante aussi et ensuite avec tout les plugins python desactivés

( j ai deux version identiques de pi , meme os et niveau de maj systeme et domoticz, un qui plante et l autre non ... )

**Comment by dfo92** [comment]
J'ai mieux cerné le problème. J'ai réinstallé une version propre de domo beta 8094 puis le plugin rfplayer. Tout est OK. La création des dispositifs se fait correctement et le changement d'état se passe bien (vision log) sur tous les dispositifs (6 Micro Cox + STARBOX F03). Le problème survient quand on créé un interrupteur avec un dispositif. Systématiquement, domo plante quand une mise à jour de l'état de l'interrupteur se produit. Dés qu'on sort l'interrupteur tout fonctionne normalement.
Je n'avais pas ce problème avec l'interrupteur STARBOX et l'ancienne version beta. Il faudrait que je puisse retester, mais je ne sais pas réinstaller (simplement) une ancienne version beta. Si tu as un lien sur le sujet, je suis preneur.

**Comment by dfo92** [comment]
Hello,
J'ai recompilé une version beta de juin. C'est de nouveau stable. Mais de temps en temps le plugin recréé un dispositif déjà existant et l'ancien ne change pus d'état. En pj le log de création si çà peut être utile.
"Devices already exist. Unit=13" mais l'ancien unit est 10 et 13 est le nouveau dispositif !

[double microcox.txt](https://github.com/sasu-drooz/Domoticz-Rfplayer/files/1163290/double.microcox.txt)

**Comment by zaraki673** [comment]
Salut, dois y avoir une erreur dans ta log, je le vois juste mettre a jour
le statut ?

je vais voir pour optimiser la recherche des dispositifs existants, avec un
peu de chance ca devrait resoudre le problème
;)

**Comment by dfo92** [comment]
Oui, peut-être que j'ai raté l'erreur, mais je te remets un log qui recréé aussi un dispositif existant avec une erreur de décodage. On voit apparaitre un nouveau qualifier (10) un peu plus complexe

[qualifier.txt](https://github.com/sasu-drooz/Domoticz-Rfplayer/files/1163765/qualifier.txt)

**Comment by zaraki673** [comment]
correction appporté : https://github.com/sasu-drooz/Domoticz-Rfplayer/commit/e242a7ae9cd3d0fdd09ccbf287bd081f8cfe5301

je clos, a réouvrir si besoin ;)
