### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by k-sartor** [sasu-drooz/Domoticz-Rfplayer#30]
According to these messages:
"qualifier": "6", "qualifierMeaning": { "flags": ["Alarm","LowBatt"]}}}}
"qualifier": "4", "qualifierMeaning": { "flags": ["LowBatt"]}}}}
"qualifier": "2", "qualifierMeaning": { "flags": ["Alarm"]}}}}
"qualifier": "0", "qualifierMeaning": { "flags": []}}}}
"qualifier": "8", "qualifierMeaning": { "flags": ["Supervisor/Alive"]}}}}
"qualifier": "12", "qualifierMeaning": { "flags": ["LowBatt","Supervisor/Alive"]}}}}

Here are a proposed improvement for Visionic MCT-320
I don't know how use git for propose update

if qualifier =="8" or qualifier=="4" or qualifier=="12" or qualifier=="0":
	status=0
if qualifier == "1" :
	status=10
if qualifier =="7" or qualifier=="2" or qualifier=="6":
	status=20
if qualifier == "3" :
	status=30
Battery=99
if qualifier == "4" or qualifier =="6" or qualifier =="12":
	Battery=10

**Comment by zaraki673** [comment]
Thank's for your help, wil try tu update as soon as possible

**Comment by zaraki673** [comment]
fix with https://github.com/sasu-drooz/Domoticz-Rfplayer/issues/20
