### ISSUE TITLE
'onMessage' failed

### ISSUE THREAD

**Issue by rom289** [sasu-drooz/Domoticz-Rfplayer#39]
Bonjour,

Depuis quelques temps, j'ai constaté la présence du message suivant dans mes logs : 
'onMessage' failed 'TypeError':'onMessage() takes 2 positional arguments but 4 were given'.

En ajoutant les 2 arguments suivants à la fonction, cela semble régler le problème : 
def onMessage(self, Connection, Data): -> def onMessage(self, Connection, Data, Status, Extra):
def onMessage(Connection, Data): -> def onMessage(Connection, Data, Status, Extra):

Pourtant le prototype de onMessage avec 2 arguments été valable à un moment donné.
http://www.domoticz.com/forum/viewtopic.php?t=18588

A suivre.

**Comment by zaraki673** [comment]
tu es sur quelle version ? (domoticz et la base de ton plugin avant que tu le corriges)

**Comment by rom289** [comment]
Plugin : 1.0.7
Domoticz : v3.8153

**Comment by zaraki673** [comment]
ok, domoticz en version stable, c est quelques versions avant la mise en application  :D

y a pas sur les dernières beta (enfin sur les beta depuis :p )

**Comment by rom289** [comment]
Ah ok. j'étais revenu en version stable suite à la désactivation des plugins Python. 
ça a été réactivé sur les dernières versions ??

**Comment by zaraki673** [comment]
il me semble, du moins qd j ai fais la mise à jour la semaine dernière ca fonctionnait chez moi 

fait une sauvegarde au cas ou (perso je duplique juste mon répertoire domoticz après l avoir arrêté bien sur :p )

**Comment by rom289** [comment]
Merci pour l'info. Je vais envisager de repasser en beta.

**Comment by zaraki673** [comment]
je confirme ca fonctionne en  3.8759

;)
