### ISSUE TITLE
various device unsopported

### ISSUE THREAD

**Issue by deennoo** [sasu-drooz/Domoticz-Rfplayer#4]
Hello,

please find on this link a txt file with various unsupported device

https://drive.google.com/open?id=0B46sxK2orIewV0hLa1VjelZLbHc

**Comment by zaraki673** [comment]
{ "frame" :{"header": {"frameType": "0", "cluster": "0", "dataFlag": "0", "rfLevel": "-87", "floorNoise": "-93", "rfQuality": "2", "protocol": "5", "protocolMeaning": "OREGON", "infoType": "4", "frequency": "433920"},"infos": {"subType": "0", "id_PHY": "0x6250", "id_PHYMeaning": "", "adr_channel": "10249",  "adr": "40",  "channel": "9",  "qualifier": "48",  "lowBatt": "0", "measures" : [{"type" : "temperature", "value" : "-0.0", "unit" : "Celsius"}, {"type" : "hygrometry", "value" : "0", "unit" : "%"}]}}}

==> ok for this one

**Comment by zaraki673** [comment]
INFOTYPE 6 : 
{ "frame" :{"header": {"frameType": "0", "cluster": "0", "dataFlag": "0", "rfLevel": "-76", "floorNoise": "-97", "rfQuality": "5", "protocol": "5", "protocolMeaning": "OREGON", "infoType": "6", "frequency": "433920"},"infos": {"subType": "0", "id_PHY": "0x1A89", "id_PHYMeaning": "WGR800", "adr_channel": "62464",  "adr": "244",  "channel": "0",  "qualifier": "48",  "lowBatt": "0", "measures" : [{"type" : "wind speed", "value" : "0.0", "unit" : "m/s"}, {"type" : "direction", "value" : "157", "unit" : "degree"}]}}}

==> already done for this one

**Comment by zaraki673** [comment]
Error with INFOTYPE 8
INFOTYPE 9 not yet supported (Rain sensor)

**Comment by zaraki673** [comment]
correction sur infotype 8 : https://github.com/sasu-drooz/Domoticz-Rfplayer/pull/5

**Comment by zaraki673** [comment]
Pour infotype 9 voir ici : https://github.com/sasu-drooz/Domoticz-Rfplayer/issues/2
