### ISSUE TITLE
failed to load 'plugin.py' aprés mise à jour plugin

### ISSUE THREAD

**Issue by MacAre** [sasu-drooz/Domoticz-Rfplayer#40]
Bonjour,
Le plugin ne se charge plus après avoir fait une mise à jour de 1.0.7 vers 1.0.9 sur Domoticz 3.8762 (beta) sur Raspberry PI3 (Python 3.5.3).

J'ai lancé la commande `curl -L https://raw.githubusercontent.com/sasu-drooz/Domoticz-Rfplayer/master/plugin.py > domoticz/plugins/rfplayer/plugin.py` puis `sudo systemctl restart domoticz.service`
J'ai eu l'erreur juste après.
Comme je suis en phase de tests du RFPlayer (qui détecté les RTS avant MAJ), je me suis permis de supprimer RFPlayer dans les matériels (et de perdre les équipements déjà détectés). Ca ne résout pas le pb.

J'ai tenté un batch avec ceci:

`sudo systemctl stop domoticz.service`
`sudo rm domoticz/plugins/rfplayer -R`
`mkdir domoticz/plugins/rfplayer`
`curl -L https://raw.githubusercontent.com/sasu-drooz/Domoticz-Rfplayer/master/plugin.py > domoticz/plugins/rfplayer/plugin.py`
`chmod 755 domoticz/plugins/rfplayer/plugin.py`
`sudo systemctl start domoticz.service`

mais idem, l'erreur persiste.
J'ai rebooté, idem....

Comment bien faire pour upgrader le plugin ?

**Comment by zaraki673** [comment]
c est la bonne methode, erreur de ma part ds le code :(

**Comment by MacAre** [comment]
J'ai remis la 1.0.7, ça marche même sans le chmod 755 (il est en 644).

Je viens de relancer le batch ci-dessous et cette fois c'est ok. Version 1.0.9 en place.

`sudo systemctl stop domoticz.service`
`sudo rm domoticz/plugins/rfplayer -R`
`mkdir domoticz/plugins/rfplayer`
`curl -L https://raw.githubusercontent.com/sasu-drooz/Domoticz-Rfplayer/master/plugin.py > domoticz/plugins/rfplayer/plugin.py`
`sudo systemctl start domoticz.service`

Merci ;-)
