### ISSUE TITLE
Probleme de maj des level sur les selector switch 

### ISSUE THREAD

**Issue by zaraki673** [sasu-drooz/Domoticz-Rfplayer#41]
Dès qu'un device X2D créé par le plugin rfplayer est modifié via l'interface de domoticz, la valeur de la colonne "Options" est modifiée... du coup le device n'est plus reconnu par le plugin rfplayer....

Exemple ci-dessous : les champs spécifiquement ajoutés par le plugin pour des modules de chauffages X2D ont disparu après ajout d'un 'Level' dans Domoticz (utiliser un convetisseur Base64 pour retrouver les valeurs en clair).

Contenu du champ Options avant modification :

LevelActions:fHx8fHx8fHx8;
LevelNames:T2ZmfEhHfEVjb3xNb2RlcmF0fE1lZGlvfENvbWZvcnR8QXNzb2M=;
LevelOffHidden:RmFsc2U=;
SelectorStyle:MA==;
area:MA==;
frequency:ODY4MzUw;
function:Mg==;
id:MTExMDAwMDEwMTEwMTEwMDAwMDAxMDEwMA==;
infoType:MTA=;
protocol:OA==;
subType:NQ==

Mise à jour du device par ajout d'un Level (libellé Auto) via domoticz :

LevelActions:fHx8fHx8fA==;
LevelNames:T2ZmfEhHfEVjb3xNb2RlcmF0fE1lZGlvfENvbWZvcnR8QXNzb2N8QXV0bw==;
LevelOffHidden:ZmFsc2U=;
SelectorStyle:MA==

Les champs dédiés et spécifiques aux modules de chauffage X2D ont "disparus" (area, frequency etc.)
Je pense que c'est parce qu'ils ne sont pas dans l'interface graphique de domoticz... Car je ne vois pas en quoi le plugin rfplayer intervient dans cette modification de device...

**Comment by ogulf** [comment]
Je pense que le problème ne se limite pas aux SelectorSwitch, mais bien à tous les dispositifs ayant le champ "Options" personnalisé. Et que c'est un pb Domoticz et non un pb du plugin rfplayer.

Sauf à ce que l'utilisation du champ Options soit "interdite" par les développeurs Domoticz et qu'il ait été détourné pour les besoins spécifiques du plugin rfplayer... Mais dans ce cas je ne sais pas comment le contourner...

A disposition pour aider, dans la mesure de mes capacités :)

**Comment by zaraki673** [comment]
plus de problème sur les dernière béta

a suivre
