### ISSUE TITLE
Mauvaise insertion de nouveaux devices

### ISSUE THREAD

**Issue by zzdomi** [sasu-drooz/Domoticz-Rfplayer#48]
Context:
8 sondes de temperature, 1 inter chacon, 5 récepteurs X2D, 1 zibase.
De temps en temps, j'ai des doublons dans mes devices au niveau sondes ou actionneurs.
Je me suis aperçu que dans la BdD domoticz les options des devices originaux on été écrasé par qq chose qui n'a rien a voir à l'histoire, d'où recreation.
En analysant les logs je vois que le plugin essaie de créer des devices avec un id existant:
-12-15 07:14:06.686  (rfp1) Create devices : 24
2017-12-15 07:14:06.687  (rfp1) Creating device '4 - 961677056'.
2017-12-15 07:14:06.687  Error: (rfp1) Device creation failed, Hardware/Unit combination (2:2) already exists in Domoticz.
2017-12-15 07:14:06.687  (rfp1 - Hygro - 50177 (channel 1)) Updating device from 46:'1' to have values 0:'0'.
Comme le code de retour du create n'est pas testé on enquille tranquille un update derrière.
En analysant le code je m'aperçois que l'init de la variable nbrdevices est faite que si le dernier device scanné a le même protocol et infoType alors que ceci devrait être fait à la fin de la boucle.
J'avais corrigé ceci pour les sondes de température Oregon, mais là il faut le faire pour tous les infoTypes.
=> Je m'en occupe.

**Comment by zaraki673** [comment]
merci ;)

**Comment by zaraki673** [comment]
je t'ai donné les droits d’écriture sur le git ;)

**Comment by zzdomi** [comment]
Ok, merci.
Je laisse en endurance ce WE et lundi on avise.

**Comment by zaraki673** [comment]
ca marche, j aurais plus de temps la semaine prochaine :D

2017-12-16 16:41 GMT+01:00 zzdomi <notifications@github.com>:

**Comment by zzdomi** [comment]
So far, so good:)
Plus d'erreur d'insertion.
En bonne voie pour le pull request de lundi.

**Comment by zzdomi** [comment]
Done!
