### ISSUE TITLE
Erreur sur modification du plugin

### ISSUE THREAD

**Issue by manolo75** [sasu-drooz/Domoticz-Rfplayer#52]
Bonjour,

Quand je clique sur modifier dans la page Matériel sur le plugin, celui-ci ne redémarre pas et bloque mon domoticz sur le message : 

2017-12-18 07:25:02.701  Error: (RFPlayer) Plugin did not stop after 5 seconds, waiting.

Je dois redémarrer domoticz manuellement et tout rentre dans l'ordre.

**Comment by zzdomi** [comment]
J'ai eu le même problème après avoir fait un pull sur la dernière version de domoticz.
Je suis revenu à la version 3.8786 qui ne présente pas de problème.

**Comment by manolo75** [comment]
Ok merci, je vais attendre la prochaine mise à jour de la beta alors. Tu peux fermer ce ticket.

**Comment by zzdomi** [comment]
J'ai ouvert un ticket chez domoticz pour le blocage.
Je leur ai également donné la correction: il faut commenter le "else" de la ligne 687 du fichier hardware/Plugin.cpp.

**Comment by zzdomi** [comment]
En fait la modif est plus conséquente mais a bonne nouvelle c'est que ça fonctionne de nouveau à partir de la version 3.8796
