### ISSUE TITLE
Mauvais subtype pour sonde Oregon

### ISSUE THREAD

**Issue by urluba** [sasu-drooz/Domoticz-Rfplayer#57]
Bonjour,

Tout d'abord merci beaucoup pour le plugin !

Je dispose de sondes Oregon THGR228N. Elles semblent parfaitement marcher dans Domoticz mais il n'est pas possible d'exporter leurs données dans Influx (ou autre base). La log affiche l'erreur ["Could not determine data push value" qui provient de BasePush.ccp#L687](https://github.com/domoticz/domoticz/blob/bc507f7a877fb9a47611583041536ac0c74ebc33/push/BasePush.cpp#L687) lorsque le _subtype_ n'est pas connu.

Domoticz affiche d'ailleurs un 'sous-type' à 'Unknown' pour ces dispositifs et dans _domoticz.db_, la sonde existe effectivement avec un _subtype_ à 0:
```
sqlite> select id, name, type, subtype from devicestatus;
[...]
32|Temp-Mobile|80|0
33|Hygro-Mobile|81|0
34|Temp/Hygro-Mobile|82|0
```
En assignant la bonne valeur au device 34 ([6 dans mon cas](https://github.com/domoticz/domoticz/blob/494fff71685f319b25e7824684c299162b19f8c3/main/RFXtrx.h#L884)), tout rentre dans l'ordre :)

Est-ce que le _subtype == 0_ est positionné par le plugin et si oui, est-il possible de positionner le bon subtype 'generique' (voir un mauvais :) ) ?

Merci

**Comment by zaraki673** [comment]
Bonjour,

alors si je ne me trompe ca doit etre de l'infotype4, dc modifier ici : 
https://github.com/sasu-drooz/Domoticz-Rfplayer/blob/48fa58433197a9ab03710dbf655cc49a18367a2e/plugin.py#L936

(rajouter le Subtype voulu)

**Comment by zzdomi** [comment]
Le subtype renvoyé le le rfplayer est toujours à 0 pour les sondes oregon.
Il faut tester le type pour affecter un subtype correct.
Je m'en occupe.

**Comment by zzdomi** [comment]
Merci d'essayer la version de la branche issue#57 du fork zzdomi/Domoticz-Rfplayer avant merge avec la branche officielle.

**Comment by urluba** [comment]
Yop,

c'est bon pour moi ! 

1. Sonde supprimée + recrée

2. Sonde vue ok:
![sonde corrigée](https://screenshotscdn.firefoxusercontent.com/images/3c7bbf07-4ce2-48b7-97fb-6d6d9eea1560.png)
Curiosité le Lacrosse TX3 pour l'humidité.

3. Export ok:
![sonde corrigée](https://screenshotscdn.firefoxusercontent.com/images/1cf73998-92fd-4e51-82a4-e4024bddeafd.png)

**Comment by zzdomi** [comment]
J'ai mis 1 dans le subtype des devices dérivés. On peut mettre une autre valeur et avoir "unknown", c'est également possible.
