### ISSUE TITLE
Plugins out

### ISSUE THREAD

**Issue by Grouick** [sasu-drooz/Domoticz-Rfplayer#59]
j'avais installé le plugins correctement, mais depuis une mise à jour domoticz, impossible de le réinstallé.
Domoticz Version: 3.8924
Build Hash: 4b5824be
Compile Date: 2018-02-19 11:50:16
dzVents Version: 2.4.1

avez vous le même souci ?

**Comment by zzdomi** [comment]
Non,

Pas de problème avec la version courante :V3.8944

**Comment by Grouick** [comment]
mon soucis c'est corrigé par une ré-installation.
cordialement
