### ISSUE TITLE
Configuration settings not available

### ISSUE THREAD

**Issue by agsd31** [sasu-drooz/Domoticz-Rfplayer#7]
![2017-04-25_23h01_05](https://cloud.githubusercontent.com/assets/12991455/25407664/7fd2731c-2a0b-11e7-8b12-7d2a5db38215.png)
![2017-04-25_23h00_30](https://cloud.githubusercontent.com/assets/12991455/25407665/7fdc48ec-2a0b-11e7-85b4-dbd7147562ea.png)
Hello, i don't understand why i can't show settings.

I am in the beta channel and uptodate.

I have followed the setup from https://github.com/sasu-drooz/Domoticz-Rfplayer/wiki/Setup

My python version seems to be ok
cf logs PluginSystem: Started, Python version '3.4.2'.

I'm a begginer with domoticz...

**Comment by zaraki673** [comment]
hi, have you try another plugin ?
if you have the same problem, should look at domoticz forum, you should have an error when installing domoticz with python plugin

**Comment by agsd31** [comment]
Hi,
I have tried with an another plugin and i have the same behaviour.
I will reinstall my domoticz from scratch.
Thank you for your plugin.
Antoine

**Comment by zaraki673** [comment]
ok,
thank's ;)
